apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
  namespace: placeholder
spec:
  type: ExternalName
  externalName: fullstack-db.c9tlsge0boez.us-east-1.rds.amazonaws.com
  ports:
    - name: port
      port: 3306
