apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  namespace: placeholder
  labels:
    app: customers
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - name: customers-container
          imagePullPolicy: Always
          image: bryan949/poc-customers:latest
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
                - touch
                - healthy
          env:
            - name: JDBC_DATASOURCE
              valueFrom:
                configMapKeyRef:
                  name: poc-config
                  key: JDBC_DATASOURCE
            - name: JDBC_USER
              valueFrom:
                secretKeyRef:
                  name: poc-secret
                  key: JDBC_USER
            - name: JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: poc-secret
                  key: JDBC_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: placeholder
  labels:
    app: customers
spec:
  type: ClusterIP
  selector:
    app: customers
  ports:
    - protocol: TCP
      #service's port that pods use to interact
      port: 80
      #pod port
      targetPort: 80
